### ISSUE TITLE
Breaking up an application monolith with NSM

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/cmd-nse-simple-vl3-docker#1]
There are many existing applications in the world which consist of a collection of monolith servers:

![Breaking up the Monolith with NSM-Page-1](https://user-images.githubusercontent.com/1455208/161762487-4c59bd0f-0fc8-41e7-830b-3787dce71c27.svg)

running multiple services on those servers, with each user sharded to exactly one monolith server.

It is desirable to be able to progressively break such monoliths up into cloud native apps bit by bit by pulling services out into Pods:

![Breaking up the Monolith with NSM-Page-2](https://user-images.githubusercontent.com/1455208/161763551-5ebdf0ef-d7d9-4dff-a71d-a595f16f7178.svg)

The problem then becomes how to establish communications between these services that have been pulled into Pods and those services that remain on the monolith.  NSM offers an ideal way to do so.

By creating a docker based combination of vL3/forwarder/nsc to run on the monolith server, and registering it with a floating network service domain, Pods running services can connect to it using NSM and communicate with one another:

![Breaking up the Monolith with NSM-Page-3](https://user-images.githubusercontent.com/1455208/161764611-e7f1c5f8-f38f-485e-958b-d88455c13b98.svg)

Because the cmd-nse-simple-vl3-docker is runs on a bare server, it cannot rely on a forwarder and must provide that functionality itself.  Its probably best to think of it as a hybrid between a vl3 nse that takes its IPAM from a simple env variable containing the prefix for IPAM (point2pointipam), the parts of a forwarder that would handle wireguard and kernel interfaces, and a simple built in client to 'request' a local kernel interface on the server.

The cmd-nse-simple-vl3-docker would need to be run as a docker container (not a pod) in the host netns in privileged mode.
It would need to:

1.  Opportunistically binds with AF_PACKET to the host interface in a manner similar to the cmd-forwarder-vpp
2. Supports local mechanism kernel and remote mechanism wireguard.  Connections for either one get plugged into the vl3 vrf.
3. On startup, should make its own 'local' request for a kernel interface on the host.
4. Advertises a named networkservice that semantically provides a very simple vl3.  that simple vl3 can use simple point2point ipam using a prefix it receives from an environment variable.

Once registered, it could then accept incoming wireguard vWires from Pods running in what ever K8s cluster they are running in.

Since there will be exactly one kernel interface local to the monolith server attached to the vL3, it will behave like a 'local to the monolith server' vL3.

**Comment by denis-tingaikin** [comment]
I think for 

>2.  **DNS** - k8s and docker container should know about each other

We can do setup of DNS as we do for interdomain

**Comment by denis-tingaikin** [comment]
> 3. **Create a chain** - it is be a combination of nsmgr/forwarder/vl3/nsc

I feel its not a chain elemnt. Its implementation of cmd-nse-simple-vl3-docker

**Comment by edwarnicke** [comment]
@glazychev-art This is about right.  I'd suggest starting with step 3 (create a chain).   @denis-tingaikin Is right, we probably have all the chain elements we need already... it should mostly be a matter of composition.

You are correct to call out that we will need to work out the spire bits.  I suspect we can get something *working* from having the chain/cmd + figuring out the spire bits.  From there adding DNS will be al layering on issue, which I suspect @denis-tingaikin has some solution to for interdomain.  But lets get basic vL3 going before we worry about the DNS parts.

**Comment by glazychev-art** [comment]
@edwarnicke 
Additional thing - our current `cmd-nse-vl3-vpp` is completely based on vpp and uses [memif interfaces](https://github.com/networkservicemesh/cmd-nse-vl3-vpp/blob/main/main.go#L413). 
Therefore [loopback](https://github.com/networkservicemesh/sdk-vpp/tree/main/pkg/networkservice/loopback), [unnumbered](https://github.com/networkservicemesh/sdk-vpp/tree/main/pkg/networkservice/connectioncontext/ipcontext/unnumbered) and [vrf](https://github.com/networkservicemesh/sdk-vpp/tree/main/pkg/networkservice/vrf) are created **_only_** for vpp.

In this issue we are talking about kernel interfaces.
**_Question_**:  do I understand correctly that we should create similar chain-elements (loop, vrf, unnumbered), but for the `sdk-kernel`?

**Comment by edwarnicke** [comment]
@glazychev-art We'd still use vpp in the container, we need it to run the vrf, handle vWires, etc.

**Comment by edwarnicke** [comment]
@glazychev-art You'd just use the mechanisms for kernel and wireguard instead of memif

**Comment by glazychev-art** [comment]
@edwarnicke 
Yes, we will use vpp in the container. I think it looks like this:
![Screenshot from 2022-04-19 21-00-26](https://user-images.githubusercontent.com/17748275/164021559-6dd6ef4e-4e00-404b-9b05-d973587ca57c.png)

**_Only_** kernel side has IP address. So, we also need to create vrf, loop on the **kernel** side and we need new chain elements for the `sdk-kernel`.

Do I understand correctly?

**Comment by edwarnicke** [comment]
@glazychev-art Looking at your diagram more... I'd actually put creating loop, vrf, un numbered in the 'server part'.

**Comment by edwarnicke** [comment]
Basically... unlike a forwarder which 'cross connects'.. you just need to have a server which takes 'connections' and can do its own kernel interface mechanics to connect to the VRF.

**Comment by glazychev-art** [comment]
Closed with https://github.com/networkservicemesh/cmd-nse-simple-vl3-docker/pull/4 and https://github.com/networkservicemesh/integration-k8s-kind/pull/669
