### ISSUE TITLE
Allow setting of registration url via env variable

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/cmd-nse-simple-vl3-docker#119]
For the monolith case, it is sometimes necessary due to NAT to register the NSE with a IP or DNS domain name that is *different* from the [listenOn](https://github.com/networkservicemesh/cmd-nse-simple-vl3-docker/blob/main/main.go#L347) IP.  

For this reason, we should allow the setting of an ENV variable "NSM_REGISTER_AS_URL" which can be set to an IP address or DNS domain name and used to register the NSE using that URL instead of the listenOn IP.

In this way someone running the container with docker or docker compose could simply set that env variable to register with an alternate public IP or a DNS domain name that would resolve to the correct public IP.

**Comment by edwarnicke** [comment]
@trastle is this what you are looking for?

**Comment by denis-tingaikin** [comment]
@trastle , @edwarnicke Does the issue still actual? Could we schedule it in this release?

**Comment by denis-tingaikin** [comment]
@edwarnicke I think it should be easy to fix and it makes sense. 

@bellycat77 Would you have a look?

**Comment by edwarnicke** [comment]
@denis-tingaikin Please do

**Comment by denis-tingaikin** [comment]
Seems like done
